apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubeapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp 
    spec:
      containers:
        - name: kubeapp 
          image: admcoeacr.azurecr.io/kubeapp
          ports:
          - containerPort: 80
---
     
apiVersion: v1
kind: Service
metadata:
    name: kubeapp
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: kubeapp
